### ISSUE TITLE
Invalid Column Name

### ISSUE THREAD

**Issue by kazuwal** [PacktPublishing/Data-Engineering-with-Apache-Spark-Delta-Lake-and-Lakehouse#2]
Hi I am going through the book and come across the following error with the batch pipeline.

**Lookup New Watermark** fails with the following error:

`Activity failed because an inner activity failed; Inner activity name: Lookup New Watermark, Error: Failure happened on 'Source' side. ErrorCode=SqlOperationFailed,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=A database operation failed with the following error: 'Invalid column name 'updated_at'.',Source=,''Type=System.Data.SqlClient.SqlException,Message=Invalid column name 'updated_at'.,Source=.Net SqlClient Data Provider,SqlErrorNumber=207,Class=16,ErrorCode=-2146232060,State=1,Errors=[{Class=16,Number=207,State=1,Message=Invalid column name 'updated_at'.,},],'`

**Comment by kazuwal** [comment]
<img width="1930" alt="Screenshot 2021-12-13 at 15 28 32" src="https://user-images.githubusercontent.com/6560983/145840144-440c56d1-691f-44e5-b8c6-fea78864ef56.png">

**Comment by mkukreja1** [comment]
The blue arrows on the failed activity will tell you which table was being looked up for the new watermark. Once you know the name of the table you can go to Azure SQL query editor and verify that the table in question has the "updated_at" column. Since your other Lookup activities were successful I am guessing there may be a typo somewhere.

**Comment by kazuwal** [comment]
I can see  the issue now. The output from **Find SalesDB Tables** returns **[sys].[ipv6_database_firewall_rules]** for some reason. This table does not have the 'updated_at' column. Im pretty certain I am using the exact query referenced in the book...

```
{
    "count": 4,
    "value": [
        {
            "Table_Name": "[sys].[ipv6_database_firewall_rules]"
        },
        {
            "Table_Name": "[dbo].[products]"
        },
        {
            "Table_Name": "[dbo].[store_customers]"
        },
        {
            "Table_Name": "[dbo].[store_orders]"
        }
    ],
    ...
}
```
Query ...

```
SELECT QUOTENAME(table_schema)+'.'+QUOTENAME(table_name) AS Table_Name FROM information_Schema.tables WHERE table_name not in ('watermarktable', 'database_firewall_rules')
```

**Comment by kazuwal** [comment]
I fixed the issue by just adding the view **ipv6_database_firewall_rules** missing from the query filter:

```
SELECT QUOTENAME(table_schema)+'.'+QUOTENAME(table_name) AS Table_Name FROM INFORMATION_SCHEMA.tables WHERE Table_Name not in ('watermarktable', 'database_firewall_rules', 'ipv6_database_firewall_rules')
```
